### PR TITLE
[JBEAP-20946] Eliminating not existing Java encoding names

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/JBEAP-20946

### CODE REVIEW

**Comment by ropalka** [comment]
@scottmarlow please review

**Comment by scottmarlow** [comment]
@ropalka I'm guessing that some Java SE implementations might include support for the Java encoding names that we are removing.  I'm guessing that Java on an IBM mainframe would need to support the various `EBCDIC` encoding names since 'EBCDIC` is typically used on the IBM mainframe (with the exception of running Linux which I think uses `ASCII` character sets).

Could this bug be fixed without removing Java encoding names that might be included in some Java SE implementations?

**Comment by ropalka** [comment]
@scottmarlow your guess was totally right and thus my initial PR proposal was wrong.
I updated PR as you suggested i.e. without removing Java encoding names from the config file.
Since now on we will register particular Java charset name into internal collections if and only if
configured Java charset name is supported on particular JDK. Please review again Scott.

**Comment by scottmarlow** [comment]
Should we create an upstream pull request on https://github.com/apache/xalan-j as well?

**Comment by ropalka** [comment]
Does it make sense @scottmarlow ? I see [Xalan](https://github.com/apache/xalan-j/commits/trunk) is dead project - last code change almost 7 years ago.

**Comment by scottmarlow** [comment]
I see two possibilities:
1. Apache Xalan will not release any new versions or merge any of the (few) pending pull requests.
2. Or someone will do a new release of Xalan in the future that may include pull requests.

Currently, it does look like #1 is currently true but hard to know if/when #2 might happen.

**Pull request merged**
